<template>
  <div id="category">
     <h2>分类</h2>
    <scroll class="content" :probeType="2">
      <button @click="Click">点击1</button>
      <div @click="divClick">点击2</div>
      <ul>
        <li>分类列表1</li>
        <li>分类列表2</li>
        <li>分类列表3</li>
        <li>分类列表4</li>
        <li>分类列表5</li>
        <li>分类列表6</li>
        <li>分类列表7</li>
        <li>分类列表8</li>
        <li>分类列表9</li>
        <li>分类列表10</li>
        <li>分类列表11</li>
        <li>分类列表12</li>
        <li>分类列表13</li>
        <li>分类列表14</li>
        <li>分类列表15</li>
        <li>分类列表16</li>
        <li>分类列表17</li>
        <li>分类列表18</li>
        <li>分类列表19</li>
        <li>分类列表20</li>
        <li>分类列表21</li>
        <li>分类列表22</li>
        <li>分类列表23</li>
        <li>分类列表24</li>
        <li>分类列表25</li>
        <li>分类列表26</li>
        <li>分类列表27</li>
        <li>分类列表28</li>
        <li>分类列表29</li>
        <li>分类列表30</li>
        <li>分类列表31</li>
        <li>分类列表32</li>
        <li>分类列表33</li>
        <li>分类列表34</li>
        <li>分类列表35</li>
        <li>分类列表36</li>
        <li>分类列表37</li>
        <li>分类列表38</li>
        <li>分类列表39</li>
        <li>分类列表40</li>
        <li>分类列表41</li>
        <li>分类列表42</li>
        <li>分类列表43</li>
        <li>分类列表44</li>
        <li>分类列表45</li>
        <li>分类列表46</li>
        <li>分类列表47</li>
        <li>分类列表48</li>
        <li>分类列表49</li>
        <li>分类列表50</li>
        <li>分类列表51</li>
        <li>分类列表52</li>
        <li>分类列表53</li>
        <li>分类列表54</li>
        <li>分类列表55</li>
        <li>分类列表56</li>
        <li>分类列表57</li>
        <li>分类列表58</li>
        <li>分类列表59</li>
        <li>分类列表60</li>
        <li>分类列表61</li>
        <li>分类列表62</li>
        <li>分类列表63</li>
        <li>分类列表64</li>
        <li>分类列表65</li>
        <li>分类列表66</li>
        <li>分类列表67</li>
        <li>分类列表68</li>
        <li>分类列表69</li>
        <li>分类列表70</li>
        <li>分类列表71</li>
        <li>分类列表72</li>
        <li>分类列表73</li>
        <li>分类列表74</li>
        <li>分类列表75</li>
        <li>分类列表76</li>
        <li>分类列表77</li>
        <li>分类列表78</li>
        <li>分类列表79</li>
        <li>分类列表80</li>
        <li>分类列表81</li>
        <li>分类列表82</li>
        <li>分类列表83</li>
        <li>分类列表84</li>
        <li>分类列表85</li>
        <li>分类列表86</li>
        <li>分类列表87</li>
        <li>分类列表88</li>
        <li>分类列表89</li>
        <li>分类列表90</li>
        <li>分类列表91</li>
        <li>分类列表92</li>
        <li>分类列表93</li>
        <li>分类列表94</li>
        <li>分类列表95</li>
        <li>分类列表96</li>
        <li>分类列表97</li>
        <li>分类列表98</li>
        <li>分类列表99</li>
        <li>分类列表100</li>
        <li>分类列表101</li>
        <li>分类列表102</li>
        <li>分类列表103</li>
        <li>分类列表104</li>
        <li>分类列表105</li>
        <li>分类列表106</li>
        <li>分类列表107</li>
        <li>分类列表108</li>
        <li>分类列表109</li>
        <li>分类列表110</li>
        <li>分类列表111</li>
        <li>分类列表112</li>
        <li>分类列表113</li>
        <li>分类列表114</li>
        <li>分类列表115</li>
        <li>分类列表116</li>
        <li>分类列表117</li>
        <li>分类列表118</li>
        <li>分类列表119</li>
        <li>分类列表120</li>
        <li>分类列表121</li>
        <li>分类列表122</li>
        <li>分类列表123</li>
        <li>分类列表124</li>
        <li>分类列表125</li>
        <li>分类列表126</li>
        <li>分类列表127</li>
        <li>分类列表128</li>
        <li>分类列表129</li>
        <li>分类列表130</li>
        <li>分类列表131</li>
        <li>分类列表132</li>
        <li>分类列表133</li>
        <li>分类列表134</li>
        <li>分类列表135</li>
        <li>分类列表136</li>
        <li>分类列表137</li>
        <li>分类列表138</li>
        <li>分类列表139</li>
        <li>分类列表140</li>
        <li>分类列表141</li>
        <li>分类列表142</li>
        <li>分类列表143</li>
        <li>分类列表144</li>
        <li>分类列表145</li>
        <li>分类列表146</li>
        <li>分类列表147</li>
        <li>分类列表148</li>
        <li>分类列表149</li>
        <li>分类列表150</li>
        <li>分类列表151</li>
        <li>分类列表152</li>
        <li>分类列表153</li>
        <li>分类列表154</li>
        <li>分类列表155</li>
        <li>分类列表156</li>
        <li>分类列表157</li>
        <li>分类列表158</li>
        <li>分类列表159</li>
        <li>分类列表160</li>
        <li>分类列表161</li>
        <li>分类列表162</li>
        <li>分类列表163</li>
        <li>分类列表164</li>
        <li>分类列表165</li>
        <li>分类列表166</li>
        <li>分类列表167</li>
        <li>分类列表168</li>
        <li>分类列表169</li>
        <li>分类列表170</li>
        <li>分类列表171</li>
        <li>分类列表172</li>
        <li>分类列表173</li>
        <li>分类列表174</li>
        <li>分类列表175</li>
        <li>分类列表176</li>
        <li>分类列表177</li>
        <li>分类列表178</li>
        <li>分类列表179</li>
        <li>分类列表180</li>
        <li>分类列表181</li>
        <li>分类列表182</li>
        <li>分类列表183</li>
        <li>分类列表184</li>
        <li>分类列表185</li>
        <li>分类列表186</li>
        <li>分类列表187</li>
        <li>分类列表188</li>
        <li>分类列表189</li>
        <li>分类列表190</li>
        <li>分类列表191</li>
        <li>分类列表192</li>
        <li>分类列表193</li>
        <li>分类列表194</li>
        <li>分类列表195</li>
        <li>分类列表196</li>
        <li>分类列表197</li>
        <li>分类列表198</li>
        <li>分类列表199</li>
        <li>分类列表200</li>
        <li>分类列表201</li>
        <li>分类列表202</li>
        <li>分类列表203</li>
        <li>分类列表204</li>
        <li>分类列表205</li>
        <li>分类列表206</li>
        <li>分类列表207</li>
        <li>分类列表208</li>
        <li>分类列表209</li>
        <li>分类列表210</li>
        <li>分类列表211</li>
        <li>分类列表212</li>
        <li>分类列表213</li>
        <li>分类列表214</li>
        <li>分类列表215</li>
        <li>分类列表216</li>
        <li>分类列表217</li>
        <li>分类列表218</li>
        <li>分类列表219</li>
        <li>分类列表220</li>
        <li>分类列表221</li>
        <li>分类列表222</li>
        <li>分类列表223</li>
        <li>分类列表224</li>
        <li>分类列表225</li>
        <li>分类列表226</li>
        <li>分类列表227</li>
        <li>分类列表228</li>
      </ul> 
    </scroll>
  </div>
</template>

<script>
import Scroll from 'components/common/scroll/Scroll.vue'
export default {
  name: "Category",
  components:{
    Scroll
  },
  data(){
    return{
    }
  },
  methods:{
    Click(){
      console.log(1);
    },
    divClick(){
      console.log(2);
    }
  }
};
</script>

<style scoped> 
.content{
  height: 90vh;
  overflow: hidden;
  background-color: rgb(211, 162, 144);
}
</style>