<template>
  <div id="profile">
    <h1>个人</h1>
    <ul>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
    </ul>
  </div>
</template>

<script>
export default {
  name: "Profile",
};
</script>

<style scoped>
</style>