<template>
  <div id="cart">
    <h1>购物车</h1>
      <scroll class="content" :probeType="0">
       <ul>
        <li>购物车列表1</li>
        <li>购物车列表2</li>
        <li>购物车列表3</li>
        <li>购物车列表4</li>
        <li>购物车列表5</li>
        <li>购物车列表6</li>
        <li>购物车列表7</li>
        <li>购物车列表8</li>
        <li>购物车列表9</li>
        <li>购物车列表10</li>
        <li>购物车列表11</li>
        <li>购物车列表12</li>
        <li>购物车列表13</li>
        <li>购物车列表14</li>
        <li>购物车列表15</li>
        <li>购物车列表16</li>
        <li>购物车列表17</li>
        <li>购物车列表18</li>
        <li>购物车列表19</li>
        <li>购物车列表20</li>
        <li>购物车列表21</li>
        <li>购物车列表22</li>
        <li>购物车列表23</li>
        <li>购物车列表24</li>
        <li>购物车列表25</li>
        <li>购物车列表26</li>
        <li>购物车列表27</li>
        <li>购物车列表28</li>
        <li>购物车列表29</li>
        <li>购物车列表30</li>
        <li>购物车列表31</li>
        <li>购物车列表32</li>
        <li>购物车列表33</li>
        <li>购物车列表34</li>
        <li>购物车列表35</li>
        <li>购物车列表36</li>
        <li>购物车列表37</li>
        <li>购物车列表38</li>
        <li>购物车列表39</li>
        <li>购物车列表40</li>
        <li>购物车列表41</li>
        <li>购物车列表42</li>
        <li>购物车列表43</li>
        <li>购物车列表44</li>
        <li>购物车列表45</li>
        <li>购物车列表46</li>
        <li>购物车列表47</li>
        <li>购物车列表48</li>
        <li>购物车列表49</li>
        <li>购物车列表50</li>
        <li>购物车列表51</li>
        <li>购物车列表52</li>
        <li>购物车列表53</li>
        <li>购物车列表54</li>
        <li>购物车列表55</li>
        <li>购物车列表56</li>
        <li>购物车列表57</li>
        <li>购物车列表58</li>
        <li>购物车列表59</li>
        <li>购物车列表60</li>
        <li>购物车列表61</li>
        <li>购物车列表62</li>
        <li>购物车列表63</li>
        <li>购物车列表64</li>
        <li>购物车列表65</li>
        <li>购物车列表66</li>
        <li>购物车列表67</li>
        <li>购物车列表68</li>
        <li>购物车列表69</li>
        <li>购物车列表70</li>
        <li>购物车列表71</li>
        <li>购物车列表72</li>
        <li>购物车列表73</li>
        <li>购物车列表74</li>
        <li>购物车列表75</li>
        <li>购物车列表76</li>
        <li>购物车列表77</li>
        <li>购物车列表78</li>
        <li>购物车列表79</li>
        <li>购物车列表80</li>
        <li>购物车列表81</li>
        <li>购物车列表82</li>
        <li>购物车列表83</li>
        <li>购物车列表84</li>
        <li>购物车列表85</li>
        <li>购物车列表86</li>
        <li>购物车列表87</li>
        <li>购物车列表88</li>
        <li>购物车列表89</li>
        <li>购物车列表90</li>
        <li>购物车列表91</li>
        <li>购物车列表92</li>
        <li>购物车列表93</li>
        <li>购物车列表94</li>
        <li>购物车列表95</li>
        <li>购物车列表96</li>
        <li>购物车列表97</li>
        <li>购物车列表98</li>
        <li>购物车列表99</li>
        <li>购物车列表100</li>
        <li>购物车列表101</li>
        <li>购物车列表102</li>
        <li>购物车列表103</li>
        <li>购物车列表104</li>
        <li>购物车列表105</li>
        <li>购物车列表106</li>
        <li>购物车列表107</li>
        <li>购物车列表108</li>
        <li>购物车列表109</li>
        <li>购物车列表110</li>
        <li>购物车列表111</li>
        <li>购物车列表112</li>
        <li>购物车列表113</li>
        <li>购物车列表114</li>
        <li>购物车列表115</li>
        <li>购物车列表116</li>
        <li>购物车列表117</li>
        <li>购物车列表118</li>
        <li>购物车列表119</li>
        <li>购物车列表120</li>
        <li>购物车列表121</li>
        <li>购物车列表122</li>
        <li>购物车列表123</li>
        <li>购物车列表124</li>
        <li>购物车列表125</li>
        <li>购物车列表126</li>
        <li>购物车列表127</li>
        <li>购物车列表128</li>
        <li>购物车列表129</li>
        <li>购物车列表130</li>
        <li>购物车列表131</li>
      </ul> 
    </scroll>
  </div>
</template>

<script>
import Scroll from 'components/common/scroll/Scroll.vue'
export default {
  naem: "Cart",
  components:{
    Scroll
  },
};
</script>

<style scoped> 
.content{
  height: 300px;
  background-color: bisque;
  color: #333;
  overflow: hidden;
}
</style>